### ISSUE TITLE
Kotlin/JS example

### ISSUE THREAD

**Issue by gad2103** [fb64/grpc-fullstack-demo#19]
Hi there. This is a very cool repo. I'm interested in using this architecture but with kotlin everywhere. I would love to understand how to wrap the js stuff in kotlin JS so I could use a generated client in a react app. 

Would love your thoughts on this!

**Comment by fb64** [comment]
Hi, thank you for your interesting !  
That's been a while since I created this example (I should  update it :) )
For the JS client part I guess that you could create a simple JS module with only the WEB-GRPC client part and import it in your Kotlin-JS project .... I don't think that it's possible (for now) to generate a full kotlin client and compile it with kotlin-js as it use java dependencies. It could be great to have a Kotlin Native client generation and use it both on JVM and JS part.
